### ISSUE TITLE
CI incorrectly tries to publish kserve-web-app in track/0.10

### ISSUE THREAD

**Issue by i-chvets** [canonical/kserve-operators#156]
# Bug Description

`kserve-web-app` is not available in 1.7 relase (i.e. track/0..10)
CI is trying to publish this charm and fails.

# To Reproduce
Create a debug PR and observe failure in Publish workflow https://github.com/canonical/kserve-operators/blob/main/.github/workflows/publish.yaml
Example of failing PR: https://github.com/canonical/kserve-operators/pull/155

# Environment
Publish action in this repository https://github.com/canonical/kserve-operators/blob/main/.github/workflows/publish.yaml

# Relevant Log Output
```
/snap/bin/charmcraft upload-resource --quiet kserve-web-app kserve-web-app-image --image a84dea08430b
Store operation failed:
- resource-not-found: No oci-image type "kserve-web-app-image" resource found
Full execution log: '/home/runner/.local/state/charmcraft/log/charmcraft-20230824-153552.895475.log'
Error: The process '/snap/bin/charmcraft' failed with exit code 1
Error: Error: The process '/snap/bin/charmcraft' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/canonical/charming-actions/2.3.0/dist/upload-charm/index.js:3763:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/canonical/charming-actions/2.3.0/dist/upload-charm/index.js:3746:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/canonical/charming-actions/2.3.0/dist/upload-charm/index.js:3640:27)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
/usr/bin/sudo test -d /root/snap/charmcraft/common/cache/charmcraft/log
No charmcraft logs generated, skipping artifact upload.
```
# Additional Context
There were fixes merged into main branch that addressed this problem:
https://github.com/canonical/kserve-operators/pull/141

In particular this change needs to be cherry picked into track/0.10 branch:
https://github.com/canonical/kserve-operators/pull/141/commits/1263f31763286dc3155f354d19de6d7f9f1472a8

**Comment by kimwnasptd** [comment]
@i-chvets should this still be open?

**Comment by i-chvets** [comment]
@kimwnasptd Incorrect publishing of PR is fixed in #157
