### ISSUE TITLE
`kserve-controller` blocked with `Failed to replan` configmap not found

### ISSUE THREAD

**Issue by NohaIhab** [canonical/kserve-operators#176]
### Bug Description

during installation, `kserve-controller` goes to blocked due to the configmap not being created yet. The `kserve-controller` pebble service is started before the manifests are applied. 
Eventually, the service is restarted after the manifests are applied, so the error is observed to be temporary.
A potential fix is to check for resources before starting the service, [example in chisme](https://github.com/canonical/charmed-kubeflow-chisme/blob/main/src/charmed_kubeflow_chisme/components/kubernetes_component.py#L68)

### To Reproduce
```
juju deploy istio-pilot --channel=latest/edge --trust --config default-gateway=test-gateway
juju deploy istio-gateway istio-ingressgateway --channel=latest/edge --trust --config kind=ingress
juju relate istio-pilot istio-ingressgateway
juju deploy kserve-controller --channel=latest/edge --trust 
juju relate istio-pilot kserve-controller
```
### Environment

juju 3.1/stable
microk8s 1.25-strict/stable

### Relevant Log Output

```shell
unit-kserve-controller-0: 20:52:52 ERROR unit.kserve-controller/0.juju-log Failed to handle <InstallEvent via KServeControllerCharm/on/install[1]> with error: Please relate to istio-pilot:gateway-info
unit-kserve-controller-0: 20:52:56 ERROR unit.kserve-controller/0.juju-log Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-kserve-controller-0/charm/venv/charmed_kubeflow_chisme/pebble/_update_layer.py", line 31, in update_layer
    container.replan()
  File "/var/lib/juju/agents/unit-kserve-controller-0/charm/venv/ops/model.py", line 1894, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-kserve-controller-0/charm/venv/ops/pebble.py", line 1658, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-kserve-controller-0/charm/venv/ops/pebble.py", line 1739, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "kserve-controller" (cannot start service: exited quickly with code 1)
----- Logs from task 0 -----
2023-09-18T20:52:56Z INFO Most recent service output:
    {"level":"info","ts":1695070375.8061404,"logger":"entrypoint","msg":"Setting up client for manager"}
    {"level":"info","ts":1695070375.8064601,"logger":"entrypoint","msg":"Setting up manager"}
    {"level":"info","ts":1695070376.2203522,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
    {"level":"info","ts":1695070376.2206912,"logger":"entrypoint","msg":"Registering Components."}
    {"level":"info","ts":1695070376.2207005,"logger":"entrypoint","msg":"Setting up KServe v1alpha1 scheme"}
    {"level":"info","ts":1695070376.2221086,"logger":"entrypoint","msg":"Setting up KServe v1beta1 scheme"}
    {"level":"error","ts":1695070376.6357884,"logger":"entrypoint","msg":"unable to get deploy config.","error":"configmaps \"inferenceservice-config\" not found","stacktrace":"runtime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
2023-09-18T20:52:56Z ERROR cannot start service: exited quickly with code 1
```

**Comment by orfeas-k** [comment]
Issue has been fixed by #246 and the charm was promoted to `0.11/stable`.
